// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_heater_screen_init(void)
{
ui_heater = lv_obj_create(NULL);
lv_obj_remove_flag( ui_heater, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_heaterPer = lv_arc_create(ui_heater);
lv_obj_set_width( ui_heaterPer, 150);
lv_obj_set_height( ui_heaterPer, 150);
lv_obj_set_x( ui_heaterPer, 0 );
lv_obj_set_y( ui_heaterPer, -49 );
lv_obj_set_align( ui_heaterPer, LV_ALIGN_CENTER );
lv_arc_set_range(ui_heaterPer, 26,32);
lv_arc_set_value(ui_heaterPer, 30);
lv_arc_set_bg_angles(ui_heaterPer,0,360);
lv_arc_set_rotation(ui_heaterPer,120);
lv_obj_set_style_arc_rounded(ui_heaterPer, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_heaterPer, lv_color_hex(0xF99345), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_heaterPer, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_heaterPer, 12, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_heaterPer, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_heaterPer, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_heaterPer, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_curheaterPerLab = lv_label_create(ui_heaterPer);
lv_obj_set_width( ui_curheaterPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_curheaterPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_curheaterPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_curheaterPerLab,"30");
lv_obj_set_style_text_font(ui_curheaterPerLab, &ui_font_Chinese32B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setheaterPerLab = lv_label_create(ui_heaterPer);
lv_obj_set_width( ui_setheaterPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setheaterPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setheaterPerLab, 0 );
lv_obj_set_y( ui_setheaterPerLab, 30 );
lv_obj_set_align( ui_setheaterPerLab, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_setheaterPerLab,"设置温度℃");
lv_obj_set_style_text_color(ui_setheaterPerLab, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setheaterPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setheaterPerLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_addheaterPer = lv_button_create(ui_heater);
lv_obj_set_width( ui_addheaterPer, 32);
lv_obj_set_height( ui_addheaterPer, 32);
lv_obj_set_x( ui_addheaterPer, 80 );
lv_obj_set_y( ui_addheaterPer, 20 );
lv_obj_set_align( ui_addheaterPer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_addheaterPer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_addheaterPer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_addheaterPer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_addheaterPer, lv_color_hex(0xE2E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_addheaterPer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_addheaterPer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_addheaterPer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_addheaterPerLab = lv_label_create(ui_addheaterPer);
lv_obj_set_width( ui_addheaterPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_addheaterPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_addheaterPerLab, 0 );
lv_obj_set_y( ui_addheaterPerLab, -1 );
lv_obj_set_align( ui_addheaterPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_addheaterPerLab,"+");
lv_obj_set_style_text_color(ui_addheaterPerLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_addheaterPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_addheaterPerLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_difheaterPer = lv_button_create(ui_heater);
lv_obj_set_width( ui_difheaterPer, 32);
lv_obj_set_height( ui_difheaterPer, 32);
lv_obj_set_x( ui_difheaterPer, -85 );
lv_obj_set_y( ui_difheaterPer, 20 );
lv_obj_set_align( ui_difheaterPer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_difheaterPer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_difheaterPer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_difheaterPer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_difheaterPer, lv_color_hex(0xE2E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_difheaterPer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_difheaterPer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_difheaterPer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_difheaterPerLab = lv_label_create(ui_difheaterPer);
lv_obj_set_width( ui_difheaterPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_difheaterPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_difheaterPerLab, 0 );
lv_obj_set_y( ui_difheaterPerLab, -1 );
lv_obj_set_align( ui_difheaterPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_difheaterPerLab,"-");
lv_obj_set_style_text_color(ui_difheaterPerLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_difheaterPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_difheaterPerLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heaterStatus = lv_obj_create(ui_heater);
lv_obj_set_width( ui_heaterStatus, 199);
lv_obj_set_height( ui_heaterStatus, 50);
lv_obj_set_x( ui_heaterStatus, 0 );
lv_obj_set_y( ui_heaterStatus, 72 );
lv_obj_set_align( ui_heaterStatus, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_heaterStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_heaterStatus, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_heaterStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_heaterStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heaterStatusLab = lv_label_create(ui_heaterStatus);
lv_obj_set_width( ui_heaterStatusLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_heaterStatusLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_heaterStatusLab, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_heaterStatusLab,"运行中 | 温度30℃");
lv_obj_set_style_text_color(ui_heaterStatusLab, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_heaterStatusLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_heaterStatusLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heaterStatusBtn = lv_button_create(ui_heaterStatus);
lv_obj_set_width( ui_heaterStatusBtn, 32);
lv_obj_set_height( ui_heaterStatusBtn, 32);
lv_obj_set_x( ui_heaterStatusBtn, 76 );
lv_obj_set_y( ui_heaterStatusBtn, 1 );
lv_obj_set_align( ui_heaterStatusBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_heaterStatusBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_heaterStatusBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_heaterStatusBtn, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_heaterStatusBtn, lv_color_hex(0xF99345), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_heaterStatusBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_heaterStatusBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_heaterStatusBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heaterStatusImg = lv_image_create(ui_heaterStatusBtn);
lv_image_set_src(ui_heaterStatusImg, &ui_img_off_png);
lv_obj_set_width( ui_heaterStatusImg, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_heaterStatusImg, LV_SIZE_CONTENT);   /// 16
lv_obj_set_align( ui_heaterStatusImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_heaterStatusImg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_heaterStatusImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_image_recolor(ui_heaterStatusImg, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_image_recolor_opa(ui_heaterStatusImg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_heaterPer, ui_event_heaterPer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_addheaterPer, ui_event_addheaterPer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_difheaterPer, ui_event_difheaterPer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_heater, ui_event_heater, LV_EVENT_ALL, NULL);

}
