// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_light_screen_init(void)
{
ui_light = lv_obj_create(NULL);
lv_obj_remove_flag( ui_light, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lightPer = lv_arc_create(ui_light);
lv_obj_set_width( ui_lightPer, 150);
lv_obj_set_height( ui_lightPer, 150);
lv_obj_set_x( ui_lightPer, 0 );
lv_obj_set_y( ui_lightPer, -49 );
lv_obj_set_align( ui_lightPer, LV_ALIGN_CENTER );
lv_arc_set_value(ui_lightPer, 80);
lv_arc_set_bg_angles(ui_lightPer,0,360);
lv_arc_set_rotation(ui_lightPer,120);
lv_obj_set_style_arc_rounded(ui_lightPer, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_lightPer, lv_color_hex(BTNCLO), LV_PART_MAIN );
ui_object_set_themeable_style_property(ui_lightPer, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_exarc);
ui_object_set_themeable_style_property(ui_lightPer, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_exarc);
lv_obj_set_style_arc_width(ui_lightPer, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_lightPer, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_lightPer, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lightPer, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_lightinPer = lv_arc_create(ui_light);
lv_obj_set_width(ui_lightinPer, 138);
lv_obj_set_height(ui_lightinPer, 138);
lv_obj_set_x(ui_lightinPer, 0);
lv_obj_set_y(ui_lightinPer, -49);
lv_obj_set_align(ui_lightinPer, LV_ALIGN_CENTER);
lv_obj_remove_flag(ui_lightinPer, LV_OBJ_FLAG_CLICKABLE);
lv_arc_set_value(ui_lightinPer, 0);
lv_arc_set_bg_angles(ui_lightinPer, 0, 360);
lv_obj_set_style_arc_rounded(ui_lightinPer, false, LV_PART_MAIN | LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_lightinPer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_inarc);
ui_object_set_themeable_style_property(ui_lightinPer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_inarc);
lv_obj_set_style_arc_width(ui_lightinPer, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_lightinPer, false, LV_PART_MAIN | LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_lightinPer, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_lightinPer, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

ui_setLightPerLab = lv_label_create(ui_lightPer);
lv_obj_set_width( ui_setLightPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setLightPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setLightPerLab, 0 );
lv_obj_set_y( ui_setLightPerLab, 30 );
lv_obj_set_align( ui_setLightPerLab, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_setLightPerLab,"设置光度百分比");
lv_obj_set_style_text_color(ui_setLightPerLab, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setLightPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setLightPerLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_curLightPerLab = lv_label_create(ui_lightPer);
lv_obj_set_width( ui_curLightPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_curLightPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_curLightPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_curLightPerLab,"80%");
lv_obj_set_style_text_font(ui_curLightPerLab, &ui_font_Chinese32B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_addlightPer = lv_button_create(ui_light);
lv_obj_set_width( ui_addlightPer, 32);
lv_obj_set_height( ui_addlightPer, 32);
lv_obj_set_x( ui_addlightPer, 80 );
lv_obj_set_y( ui_addlightPer, 20 );
lv_obj_set_align( ui_addlightPer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_addlightPer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_addlightPer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_addlightPer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_addlightPer, lv_color_hex(0xE2E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_addlightPer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_addlightPer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_addlightPer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_addlightPerLab = lv_label_create(ui_addlightPer);
lv_obj_set_width( ui_addlightPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_addlightPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_addlightPerLab, 0 );
lv_obj_set_y( ui_addlightPerLab, -1 );
lv_obj_set_align( ui_addlightPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_addlightPerLab,"+");
lv_obj_set_style_text_color(ui_addlightPerLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_addlightPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_addlightPerLab, &ui_font_Chinese32B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_diflightPer = lv_button_create(ui_light);
lv_obj_set_width( ui_diflightPer, 32);
lv_obj_set_height( ui_diflightPer, 32);
lv_obj_set_x( ui_diflightPer, -85 );
lv_obj_set_y( ui_diflightPer, 20 );
lv_obj_set_align( ui_diflightPer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_diflightPer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_diflightPer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_diflightPer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_diflightPer, lv_color_hex(0xE2E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_diflightPer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_diflightPer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_diflightPer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_diflightPerLab = lv_label_create(ui_diflightPer);
lv_obj_set_width( ui_diflightPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_diflightPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_diflightPerLab, 0 );
lv_obj_set_y( ui_diflightPerLab, -1 );
lv_obj_set_align( ui_diflightPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_diflightPerLab,"-");
lv_obj_set_style_text_color(ui_diflightPerLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_diflightPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_diflightPerLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lightStatus = lv_obj_create(ui_light);
lv_obj_set_width( ui_lightStatus, 199);
lv_obj_set_height( ui_lightStatus, 50);
lv_obj_set_x( ui_lightStatus, 0 );
lv_obj_set_y( ui_lightStatus, 72 );
lv_obj_set_align( ui_lightStatus, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_lightStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_lightStatus, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_lightStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_lightStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lightStatusLab = lv_label_create(ui_lightStatus);
lv_obj_set_width( ui_lightStatusLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lightStatusLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lightStatusLab, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_lightStatusLab,"开灯中");
lv_obj_set_style_text_color(ui_lightStatusLab, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lightStatusLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lightStatusLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lightStatusBtn = lv_button_create(ui_lightStatus);
lv_obj_set_width( ui_lightStatusBtn, 32);
lv_obj_set_height( ui_lightStatusBtn, 32);
lv_obj_set_x( ui_lightStatusBtn, 76 );
lv_obj_set_y( ui_lightStatusBtn, 1 );
lv_obj_set_align( ui_lightStatusBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_lightStatusBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_lightStatusBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_lightStatusBtn, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_lightStatusBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_offbtn);
ui_object_set_themeable_style_property(ui_lightStatusBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_offbtn);
lv_obj_set_style_shadow_color(ui_lightStatusBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_lightStatusBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lightStatusImg = lv_image_create(ui_lightStatusBtn);
lv_image_set_src(ui_lightStatusImg, &ui_img_off_png);
lv_obj_set_width( ui_lightStatusImg, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_lightStatusImg, LV_SIZE_CONTENT);   /// 16
lv_obj_set_align( ui_lightStatusImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_lightStatusImg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_lightStatusImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_image_recolor(ui_lightStatusImg, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_image_recolor_opa(ui_lightStatusImg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lightMode = lv_obj_create(ui_light);
lv_obj_set_width( ui_lightMode, 199);
lv_obj_set_height( ui_lightMode, 50);
lv_obj_set_x( ui_lightMode, -1 );
lv_obj_set_y( ui_lightMode, 130 );
lv_obj_set_align( ui_lightMode, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_lightMode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_lightMode, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_lightMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_lightMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lightModeLab = lv_label_create(ui_lightMode);
lv_obj_set_width( ui_lightModeLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lightModeLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lightModeLab, -11 );
lv_obj_set_y( ui_lightModeLab, -11 );
lv_label_set_text(ui_lightModeLab,"模式");
lv_obj_set_style_text_font(ui_lightModeLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_atmosphereBtn = lv_button_create(ui_lightMode);
lv_obj_set_width( ui_atmosphereBtn, 30);
lv_obj_set_height( ui_atmosphereBtn, 16);
lv_obj_set_x( ui_atmosphereBtn, -72 );
lv_obj_set_y( ui_atmosphereBtn, 10 );
lv_obj_set_align( ui_atmosphereBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_atmosphereBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_atmosphereBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_atmosphereBtn, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_atmosphereBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_atmoBtn);
ui_object_set_themeable_style_property(ui_atmosphereBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_atmoBtn);
lv_obj_set_style_shadow_color(ui_atmosphereBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_atmosphereBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_atmosphereBtn, lv_color_hex(0xD4B8F6), LV_PART_MAIN  );
lv_obj_set_style_bg_opa(ui_atmosphereBtn, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_atmosphereBtnLab = lv_label_create(ui_atmosphereBtn);
lv_obj_set_width( ui_atmosphereBtnLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_atmosphereBtnLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_atmosphereBtnLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_atmosphereBtnLab,"氛围");
ui_object_set_themeable_style_property(ui_atmosphereBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_atmoBtnLab);
ui_object_set_themeable_style_property(ui_atmosphereBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_atmoBtnLab);
lv_obj_set_style_text_font(ui_atmosphereBtnLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MovieBtn = lv_button_create(ui_lightMode);
lv_obj_set_width( ui_MovieBtn, 30);
lv_obj_set_height( ui_MovieBtn, 16);
lv_obj_set_x( ui_MovieBtn, -36 );
lv_obj_set_y( ui_MovieBtn, 10 );
lv_obj_set_align( ui_MovieBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MovieBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_MovieBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_MovieBtn, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_MovieBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_movieBtn);
ui_object_set_themeable_style_property(ui_MovieBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_movieBtn);
lv_obj_set_style_shadow_color(ui_MovieBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_MovieBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MovieBtnLab = lv_label_create(ui_MovieBtn);
lv_obj_set_width( ui_MovieBtnLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MovieBtnLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_MovieBtnLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_MovieBtnLab,"观影");
ui_object_set_themeable_style_property(ui_MovieBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_movieBtnLab);
ui_object_set_themeable_style_property(ui_MovieBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_movieBtnLab);
lv_obj_set_style_text_font(ui_MovieBtnLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_romanBtn = lv_button_create(ui_lightMode);
lv_obj_set_width( ui_romanBtn, 30);
lv_obj_set_height( ui_romanBtn, 16);
lv_obj_set_x( ui_romanBtn, 0 );
lv_obj_set_y( ui_romanBtn, 10 );
lv_obj_set_align( ui_romanBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_romanBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_romanBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_romanBtn, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_romanBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_romanBtn);
ui_object_set_themeable_style_property(ui_romanBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_romanBtn);
lv_obj_set_style_shadow_color(ui_romanBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_romanBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_romanBtnLab = lv_label_create(ui_romanBtn);
lv_obj_set_width( ui_romanBtnLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_romanBtnLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_romanBtnLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_romanBtnLab,"浪漫");
ui_object_set_themeable_style_property(ui_romanBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_romanBtnLab);
ui_object_set_themeable_style_property(ui_romanBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_romanBtnLab);
lv_obj_set_style_text_font(ui_romanBtnLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_starryBtn = lv_button_create(ui_lightMode);
lv_obj_set_width( ui_starryBtn, 30);
lv_obj_set_height( ui_starryBtn, 16);
lv_obj_set_x( ui_starryBtn, 36 );
lv_obj_set_y( ui_starryBtn, 10 );
lv_obj_set_align( ui_starryBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_starryBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_starryBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_starryBtn, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_starryBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_starryBtn);
ui_object_set_themeable_style_property(ui_starryBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_starryBtn);
lv_obj_set_style_shadow_color(ui_starryBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_starryBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_starryBtnLab = lv_label_create(ui_starryBtn);
lv_obj_set_width( ui_starryBtnLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_starryBtnLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_starryBtnLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_starryBtnLab,"星空");
ui_object_set_themeable_style_property(ui_starryBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_starryBtnLab);
ui_object_set_themeable_style_property(ui_starryBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_starryBtnLab);
lv_obj_set_style_text_font(ui_starryBtnLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dailyBtn = lv_button_create(ui_lightMode);
lv_obj_set_width( ui_dailyBtn, 30);
lv_obj_set_height( ui_dailyBtn, 16);
lv_obj_set_x( ui_dailyBtn, 72 );
lv_obj_set_y( ui_dailyBtn, 10 );
lv_obj_set_align( ui_dailyBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dailyBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_dailyBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_dailyBtn, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_dailyBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_dailyBtn);
ui_object_set_themeable_style_property(ui_dailyBtn, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_dailyBtn);
lv_obj_set_style_shadow_color(ui_dailyBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_dailyBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dailyBtnLab = lv_label_create(ui_dailyBtn);
lv_obj_set_width( ui_dailyBtnLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dailyBtnLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dailyBtnLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_dailyBtnLab,"日常");
ui_object_set_themeable_style_property(ui_dailyBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_dailyBtnLab);
ui_object_set_themeable_style_property(ui_dailyBtnLab, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_dailyBtnLab);
lv_obj_set_style_text_font(ui_dailyBtnLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_lightPer, ui_event_lightPer, LV_EVENT_ALL, NULL);

lv_obj_add_event_cb(ui_lightStatusBtn, ui_event_lightStatus, LV_EVENT_ALL, NULL);

lv_obj_add_event_cb(ui_addlightPer, ui_event_addlightPer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_diflightPer, ui_event_diflightPer, LV_EVENT_ALL, NULL);



lv_obj_add_event_cb(ui_atmosphereBtn, ui_event_atmosphereBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_MovieBtn, ui_event_MovieBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_romanBtn, ui_event_romanBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_starryBtn, ui_event_starryBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dailyBtn, ui_event_dailyBtn, LV_EVENT_ALL, NULL);

lv_obj_add_event_cb(ui_light, ui_event_next, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_light, ui_event_main, LV_EVENT_ALL, NULL);

}
