// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_pump_screen_init(void)
{
ui_pump = lv_obj_create(NULL);
lv_obj_remove_flag( ui_pump, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pumpPer = lv_arc_create(ui_pump);
lv_obj_set_width( ui_pumpPer, 150);
lv_obj_set_height( ui_pumpPer, 150);
lv_obj_set_x( ui_pumpPer, 0 );
lv_obj_set_y( ui_pumpPer, -49 );
lv_obj_set_align( ui_pumpPer, LV_ALIGN_CENTER );
lv_arc_set_range(ui_pumpPer, 0,10);
lv_arc_set_value(ui_pumpPer, 5);
lv_arc_set_bg_angles(ui_pumpPer,0,360);
lv_arc_set_rotation(ui_pumpPer,120);
lv_obj_set_style_arc_rounded(ui_pumpPer, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_pumpPer, lv_color_hex(0x007AFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_pumpPer, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_pumpPer, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_pumpPer, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_pumpPer, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pumpPer, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_pumpinPer = lv_arc_create(ui_pump);
lv_obj_set_width(ui_pumpinPer, 138);
lv_obj_set_height(ui_pumpinPer, 138);
lv_obj_set_x(ui_pumpinPer, 0);
lv_obj_set_y(ui_pumpinPer, -49);
lv_obj_set_align(ui_pumpinPer, LV_ALIGN_CENTER);
lv_arc_set_value(ui_pumpinPer, 0);
lv_arc_set_bg_angles(ui_pumpinPer, 0, 360);
lv_obj_set_style_arc_rounded(ui_pumpinPer, false, LV_PART_MAIN | LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_pumpinPer, lv_color_hex(0x007AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_arc_opa(ui_pumpinPer, 31, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_pumpinPer, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_pumpinPer, false, LV_PART_MAIN | LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_pumpinPer, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
lv_obj_set_style_bg_opa(ui_pumpinPer, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

ui_curpumpPerLab = lv_label_create(ui_pumpPer);
lv_obj_set_width( ui_curpumpPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_curpumpPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_curpumpPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_curpumpPerLab,"5");
lv_obj_set_style_text_font(ui_curpumpPerLab, &ui_font_Chinese32B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_setpumpPerLab = lv_label_create(ui_pumpPer);
lv_obj_set_width( ui_setpumpPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_setpumpPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_setpumpPerLab, 0 );
lv_obj_set_y( ui_setpumpPerLab, 30 );
lv_obj_set_align( ui_setpumpPerLab, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_setpumpPerLab,"设置档位");
lv_obj_set_style_text_color(ui_setpumpPerLab, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_setpumpPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setpumpPerLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_addpumpPer = lv_button_create(ui_pump);
lv_obj_set_width( ui_addpumpPer, 32);
lv_obj_set_height( ui_addpumpPer, 32);
lv_obj_set_x( ui_addpumpPer, 80 );
lv_obj_set_y( ui_addpumpPer, 20 );
lv_obj_set_align( ui_addpumpPer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_addpumpPer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_addpumpPer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_addpumpPer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_addpumpPer, lv_color_hex(0xE2E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_addpumpPer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_addpumpPer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_addpumpPer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_addpumpPerLab = lv_label_create(ui_addpumpPer);
lv_obj_set_width( ui_addpumpPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_addpumpPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_addpumpPerLab, 0 );
lv_obj_set_y( ui_addpumpPerLab, -1 );
lv_obj_set_align( ui_addpumpPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_addpumpPerLab,"+");
lv_obj_set_style_text_color(ui_addpumpPerLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_addpumpPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_addpumpPerLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_difpumpPer = lv_button_create(ui_pump);
lv_obj_set_width( ui_difpumpPer, 32);
lv_obj_set_height( ui_difpumpPer, 32);
lv_obj_set_x( ui_difpumpPer, -85 );
lv_obj_set_y( ui_difpumpPer, 20 );
lv_obj_set_align( ui_difpumpPer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_difpumpPer, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_difpumpPer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_difpumpPer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_difpumpPer, lv_color_hex(0xE2E1E1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_difpumpPer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_difpumpPer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_difpumpPer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_difpumpPerLab = lv_label_create(ui_difpumpPer);
lv_obj_set_width( ui_difpumpPerLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_difpumpPerLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_difpumpPerLab, 0 );
lv_obj_set_y( ui_difpumpPerLab, -1 );
lv_obj_set_align( ui_difpumpPerLab, LV_ALIGN_CENTER );
lv_label_set_text(ui_difpumpPerLab,"-");
lv_obj_set_style_text_color(ui_difpumpPerLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_difpumpPerLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_difpumpPerLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpStatus = lv_obj_create(ui_pump);
lv_obj_set_width( ui_pumpStatus, 199);
lv_obj_set_height( ui_pumpStatus, 50);
lv_obj_set_x( ui_pumpStatus, 0 );
lv_obj_set_y( ui_pumpStatus, 72 );
lv_obj_set_align( ui_pumpStatus, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_pumpStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_pumpStatus, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_pumpStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_pumpStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpStatusLab = lv_label_create(ui_pumpStatus);
lv_obj_set_width( ui_pumpStatusLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pumpStatusLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pumpStatusLab, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_pumpStatusLab,"运行中 | 正常水位");
lv_obj_set_style_text_color(ui_pumpStatusLab, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pumpStatusLab, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pumpStatusLab, &ui_font_Chinese16B, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpStatusBtn = lv_button_create(ui_pumpStatus);
lv_obj_set_width( ui_pumpStatusBtn, 32);
lv_obj_set_height( ui_pumpStatusBtn, 32);
lv_obj_set_x( ui_pumpStatusBtn, 76 );
lv_obj_set_y( ui_pumpStatusBtn, 1 );
lv_obj_set_align( ui_pumpStatusBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pumpStatusBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_pumpStatusBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_pumpStatusBtn, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_pumpStatusBtn, lv_color_hex(0x007AFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pumpStatusBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_pumpStatusBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_pumpStatusBtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pumpStatusImg = lv_image_create(ui_pumpStatusBtn);
lv_image_set_src(ui_pumpStatusImg, &ui_img_off_png);
lv_obj_set_width( ui_pumpStatusImg, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_pumpStatusImg, LV_SIZE_CONTENT);   /// 16
lv_obj_set_align( ui_pumpStatusImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pumpStatusImg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_pumpStatusImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_image_recolor(ui_pumpStatusImg, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_image_recolor_opa(ui_pumpStatusImg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_pumpPer, ui_event_pumpPer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_pumpStatusBtn, ui_event_pumpStatus, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_addpumpPer, ui_event_addpumpPer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_difpumpPer, ui_event_difpumpPer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_pump, ui_event_light, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_pump, ui_event_main, LV_EVENT_ALL, NULL);

}
