// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"



void ui_QR_screen_init(void)
{
    ui_QR = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_QR, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    set_background(ui_QR);
    lv_color_t bg_color = lv_palette_lighten(LV_PALETTE_GREY, 5);
    lv_color_t fg_color = lv_palette_darken(LV_PALETTE_NONE, 4);

    lv_obj_t* qr = lv_qrcode_create(ui_QR);
    lv_qrcode_set_size(qr, 150);
    lv_qrcode_set_dark_color(qr, fg_color);
    lv_qrcode_set_light_color(qr, bg_color);
    
    /*Set data*/
    const char* data = "#小程序://蓝得之家/DYmDGanz1rW2oTu";
    lv_qrcode_update(qr, data, strlen(data));
    lv_obj_center(qr);

    /*Add a border with bg_color*/
    lv_obj_set_style_border_color(qr, bg_color, 0);
    lv_obj_set_style_border_width(qr, 5, 0);
}
