// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
static const char* weekday_cn[] = { "周日", "周一", "周二", "周三", "周四", "周五", "周六" };

static void update_date_label(void);
static void update_time_label(void);
static void timer_cb(lv_event_t* e);

void ui_standby_screen_init(void)
{
    ui_standby = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_standby, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    set_background(ui_standby);
    struct tm timeinfo = { 0 };
    time_t now = time(NULL);
    timeinfo = *localtime(&now);
    char time_str[16];

    ui_standby_dateLab = lv_label_create(ui_standby);
    lv_obj_add_flag(ui_standby_dateLab, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_align(ui_standby_dateLab, LV_ALIGN_TOP_MID,0,16);
    
    lv_label_set_text_fmt(ui_standby_dateLab, "%d %s",timeinfo.tm_mday, weekday_cn[timeinfo.tm_wday]);
    lv_obj_set_style_text_color(ui_standby_dateLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_standby_dateLab, &ui_font_Chinese16B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_standby_timeLab = lv_label_create(ui_standby);
    lv_obj_add_flag(ui_standby_timeLab, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_align(ui_standby_timeLab,LV_ALIGN_TOP_MID, 0, 48);
    strftime(time_str, sizeof(time_str), "%H:%M", &timeinfo);
    lv_label_set_text(ui_standby_timeLab, time_str);
    lv_obj_set_style_text_color(ui_standby_timeLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_standby_timeLab, &ui_font_Chinese32B, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_standby_welcomeLab = lv_label_create(ui_standby);
    lv_obj_add_flag(ui_standby_welcomeLab, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_align(ui_standby_welcomeLab,LV_ALIGN_BOTTOM_MID, 0, -16);
    lv_label_set_text(ui_standby_welcomeLab, "欢迎您 轻松养鱼##天");
    lv_obj_set_style_text_color(ui_standby_welcomeLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_standby_welcomeLab, &ui_font_Chinese16B, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backgroundImg, ui_event_standy, LV_EVENT_ALL,NULL);
    lv_timer_t* timer = lv_timer_create(timer_cb, 1000, ui_standby); // 每秒触发一次
}

// 更新日期标签的函数
static void update_date_label(void) {
    time_t now = time(NULL);
    struct tm* timeinfo = localtime(&now);
    char date_str[32];
    snprintf(date_str, sizeof(date_str), "%d %s", timeinfo->tm_mday, weekday_cn[timeinfo->tm_wday]);
    lv_label_set_text(ui_standby_dateLab, date_str);
}

// 更新时间标签的函数
static void update_time_label(void) {
    time_t now = time(NULL);
    struct tm* timeinfo = localtime(&now);
    char time_str[16];
    strftime(time_str, sizeof(time_str), "%H:%M", timeinfo);
    lv_label_set_text(ui_standby_timeLab, time_str);
}

// 定时器回调函数
static void timer_cb(lv_event_t* e) {
    static time_t last_time_update = 0;
    static time_t last_date_update = 0;
    time_t now = time(NULL);

    // 检查是否需要更新日期（每天更新一次）
    if (difftime(now, last_date_update) >= 86400) { // 86400秒 = 1天
        update_date_label();
        last_date_update = now;
    }

    // 检查是否需要更新时间（每分钟更新一次）
    if (difftime(now, last_time_update) >= 60) { // 60秒 = 1分钟
        update_time_label();
        last_time_update = now;
    }
}
