// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_strat_screen_init(void)
{
    ui_strat = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_strat, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_strat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
}
