// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

typedef struct schedule
{
    int8_t wday;
    int8_t hour;
    int8_t min;
}schedule_t;

static void generate_mask(lv_draw_buf_t* mask);

static void time_select_event_cb(lv_event_t* e);
static void weekday_select_event_cb(lv_event_t* e);
static void time_picker_cancel_event_cb(lv_event_t* e);
static void weekday_picker_confirm_event_cb(lv_event_t* e);
static void weekday_picker_cancel_event_cb(lv_event_t* e);
static void time_picker_confirm_event_cb(lv_event_t* e);

static lv_obj_t* time_picker_dialog = NULL;
static lv_obj_t* weekday_picker_dialog = NULL;
static lv_obj_t* time_label_start = NULL;
static lv_obj_t* time_label_end = NULL;

// 时间选择回调函数
static void time_select_event_cb(lv_event_t* e) {
    //lv_obj_t* btn = lv_event_get_target(e);
    //const char* btn_name = lv_obj_get_name(btn);

    //// 如果是“开始时间”按钮
    //if (strcmp(btn_name, "Start Time") == 0) {
    //    if (time_picker_dialog == NULL) {
    //        // 创建时间选择对话框
    //        time_picker_dialog = lv_obj_create(lv_scr_act());
    //        lv_obj_set_size(time_picker_dialog, 300, 200);
    //        lv_obj_align(time_picker_dialog, LV_ALIGN_CENTER, 0, 0);

    //        // 创建小时选择器
    //        lv_obj_t* hour_slider = lv_slider_create(time_picker_dialog);
    //        lv_slider_set_range(hour_slider, 0, 23);
    //        lv_slider_set_value(hour_slider, 12, LV_ANIM_OFF);
    //        lv_obj_set_size(hour_slider, 240, 20);
    //        lv_obj_align(hour_slider, LV_ALIGN_TOP_MID, 0, 10);

    //        // 创建分钟选择器
    //        lv_obj_t* minute_slider = lv_slider_create(time_picker_dialog);
    //        lv_slider_set_range(minute_slider, 0, 59);
    //        lv_slider_set_value(minute_slider, 30, LV_ANIM_OFF);
    //        lv_obj_set_size(minute_slider, 240, 20);
    //        lv_obj_align(minute_slider, LV_ALIGN_TOP_MID, 0, 50);

    //        // 创建“确定”和“取消”按钮
    //        lv_obj_t* btn_confirm = lv_btn_create(time_picker_dialog);
    //        lv_obj_align(btn_confirm, LV_ALIGN_BOTTOM_MID, -60, -10);
    //        lv_obj_t* label_confirm = lv_label_create(btn_confirm);
    //        lv_label_set_text(label_confirm, "确定");
    //        lv_obj_add_event_cb(btn_confirm, time_picker_confirm_event_cb, LV_EVENT_CLICKED, hour_slider);

    //        lv_obj_t* btn_cancel = lv_btn_create(time_picker_dialog);
    //        lv_obj_align(btn_cancel, LV_ALIGN_BOTTOM_MID, 60, -10);
    //        lv_obj_t* label_cancel = lv_label_create(btn_cancel);
    //        lv_label_set_text(label_cancel, "取消");
    //        lv_obj_add_event_cb(btn_cancel, time_picker_cancel_event_cb, LV_EVENT_CLICKED, NULL);
    //    }
    //}
    //// 如果是“结束时间”按钮
    //else if (strcmp(btn_name, "End Time") == 0) {
    //    // 同理实现结束时间选择（也可以复用相同的时间选择器）
    //}
}

// 时间选择确定回调
static void time_picker_confirm_event_cb(lv_event_t* e) {
    //lv_obj_t* hour_slider = lv_event_get_user_data(e);
    //int hour = lv_slider_get_value(hour_slider);

    //lv_obj_t* minute_slider = lv_obj_get_child(time_picker_dialog, NULL);
    //int minute = lv_slider_get_value(minute_slider);

    //// 更新时间标签
    //char time_str[10];
    //snprintf(time_str, sizeof(time_str), "%02d:%02d", hour, minute);
    //lv_label_set_text(time_label_start, time_str);

    //lv_obj_del(time_picker_dialog);  // 关闭对话框
    //time_picker_dialog = NULL;       // 清除对话框
}

// 时间选择取消回调
static void time_picker_cancel_event_cb(lv_event_t* e) {
    lv_obj_del(time_picker_dialog);  // 关闭对话框
    time_picker_dialog = NULL;       // 清除对话框
}

// 星期选择回调函数
static void weekday_select_event_cb(lv_event_t* e) {
    //if (weekday_picker_dialog == NULL) {
    //    // 创建星期选择对话框
    //    weekday_picker_dialog = lv_obj_create(lv_scr_act());
    //    lv_obj_set_size(weekday_picker_dialog, 300, 200);
    //    lv_obj_align(weekday_picker_dialog, LV_ALIGN_CENTER, 0, 0);

    //    // 创建星期选择的复选框
    //    lv_obj_t* checkbox_mon = lv_checkbox_create(weekday_picker_dialog);
    //    lv_obj_align(checkbox_mon, LV_ALIGN_TOP_LEFT, 10, 10);
    //    lv_checkbox_set_text(checkbox_mon, "周一");

    //    lv_obj_t* checkbox_tue = lv_checkbox_create(weekday_picker_dialog);
    //    lv_obj_align(checkbox_tue, LV_ALIGN_TOP_LEFT, 10, 50);
    //    lv_checkbox_set_text(checkbox_tue, "周二");

    //    lv_obj_t* checkbox_wed = lv_checkbox_create(weekday_picker_dialog);
    //    lv_obj_align(checkbox_wed, LV_ALIGN_TOP_LEFT, 10, 90);
    //    lv_checkbox_set_text(checkbox_wed, "周三");

    //    lv_obj_t* checkbox_thu = lv_checkbox_create(weekday_picker_dialog);
    //    lv_obj_align(checkbox_thu, LV_ALIGN_TOP_LEFT, 10, 130);
    //    lv_checkbox_set_text(checkbox_thu, "周四");

    //    lv_obj_t* checkbox_fri = lv_checkbox_create(weekday_picker_dialog);
    //    lv_obj_align(checkbox_fri, LV_ALIGN_TOP_LEFT, 10, 170);
    //    lv_checkbox_set_text(checkbox_fri, "周五");

    //    lv_obj_t* checkbox_sat = lv_checkbox_create(weekday_picker_dialog);
    //    lv_obj_align(checkbox_sat, LV_ALIGN_TOP_LEFT, 150, 10);
    //    lv_checkbox_set_text(checkbox_sat, "周六");

    //    lv_obj_t* checkbox_sun = lv_checkbox_create(weekday_picker_dialog);
    //    lv_obj_align(checkbox_sun, LV_ALIGN_TOP_LEFT, 150, 50);
    //    lv_checkbox_set_text(checkbox_sun, "周日");

    //    // 创建“确定”和“取消”按钮
    //    lv_obj_t* btn_confirm = lv_btn_create(weekday_picker_dialog);
    //    lv_obj_align(btn_confirm, LV_ALIGN_BOTTOM_MID, -60, -10);
    //    lv_obj_t* label_confirm = lv_label_create(btn_confirm);
    //    lv_label_set_text(label_confirm, "确定");
    //    lv_obj_add_event_cb(btn_confirm, weekday_picker_confirm_event_cb, LV_EVENT_CLICKED, NULL);

    //    lv_obj_t* btn_cancel = lv_btn_create(weekday_picker_dialog);
    //    lv_obj_align(btn_cancel, LV_ALIGN_BOTTOM_MID, 60, -10);
    //    lv_obj_t* label_cancel = lv_label_create(btn_cancel);
    //    lv_label_set_text(label_cancel, "取消");
    //    lv_obj_add_event_cb(btn_cancel, weekday_picker_cancel_event_cb, LV_EVENT_CLICKED, NULL);
    //}
}

// 星期选择确定回调
static void weekday_picker_confirm_event_cb(lv_event_t* e) {
    //lv_obj_t* checkbox_mon = lv_obj_get_child(weekday_picker_dialog, NULL);
    //bool mon = lv_checkbox_is_checked(checkbox_mon);

    //// 获取其他星期的选择状态
    //// 更新星期标签等，具体更新可根据需求来做

    //lv_obj_del(weekday_picker_dialog);  // 关闭对话框
    //weekday_picker_dialog = NULL;       // 清除对话框
}

// 星期选择取消回调
static void weekday_picker_cancel_event_cb(lv_event_t* e) {
    lv_obj_del(weekday_picker_dialog);  // 关闭对话框
    weekday_picker_dialog = NULL;       // 清除对话框
}

void ui_stratDetail_screen_init(void)
{

    ui_stratDetail = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_stratDetail, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_stratDetail, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stratDetail, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_size(&style, 100, 48);
    lv_style_set_bg_color(&style, lv_color_black());
    lv_style_set_text_color(&style, lv_color_white());
    lv_style_set_border_width(&style, 0);
    lv_style_set_radius(&style, 0);

    lv_obj_t* roller1 = lv_roller_create(ui_stratDetail);
    lv_obj_add_style(roller1, &style, 0);
    lv_obj_set_style_bg_opa(roller1, LV_OPA_50, LV_PART_SELECTED);

    lv_roller_set_options(roller1,
        "00\n"
        "01\n"
        "02\n"
        "03\n"
        "04\n"
        "05\n"
        "06\n"
        "07\n"
        "08\n"
        "09\n"
        "10\n"
        "11\n"
        "12\n"
        "13\n"
        "14\n"
        "15\n"
        "16\n"
        "17\n"
        "18\n"
        "19\n"
        "20\n"
        "21\n"
        "22\n"
        "23",
        LV_ROLLER_MODE_INFINITE);

    lv_obj_t* roller2 = lv_roller_create(ui_stratDetail);
    lv_obj_add_style(roller2, &style, 0);
    lv_obj_set_style_bg_opa(roller2, LV_OPA_50, LV_PART_SELECTED);

    lv_roller_set_options(roller2,
        "00\n"
        "05\n"
        "10\n"
        "15\n"
        "20\n"
        "25\n"
        "30\n"
        "35\n"
        "40\n"
        "45\n"
        "50\n"
        "55",
        LV_ROLLER_MODE_INFINITE);
    lv_obj_t* roller3 = lv_roller_create(ui_stratDetail);
    lv_obj_add_style(roller3, &style, 0);
    lv_obj_set_style_bg_opa(roller3, LV_OPA_50, LV_PART_SELECTED);

    lv_roller_set_options(roller3,
        "00\n"
        "01\n"
        "02\n"
        "03\n"
        "04\n"
        "05\n"
        "06\n"
        "07\n"
        "08\n"
        "09\n"
        "10\n"
        "11\n"
        "12\n"
        "13\n"
        "14\n"
        "15\n"
        "16\n"
        "17\n"
        "18\n"
        "19\n"
        "20\n"
        "21\n"
        "22\n"
        "23",
        LV_ROLLER_MODE_INFINITE);
    lv_obj_center(roller3);
    lv_roller_set_visible_row_count(roller3, 3);

    /* Create the mask to make the top and bottom part of roller faded.
     * The width and height are empirical values for simplicity*/
    LV_DRAW_BUF_DEFINE_STATIC(mask, 130, 150, LV_COLOR_FORMAT_L8);
    LV_DRAW_BUF_INIT_STATIC(mask);

    generate_mask(&mask);
    lv_obj_set_style_bitmap_mask_src(roller1, &mask, 0);

    // 创建最上面的“开始时间”和“结束时间”标签
    lv_obj_t* time_container = lv_obj_create(ui_stratDetail);
    lv_obj_set_size(time_container, LV_HOR_RES, 60);
    lv_obj_align(time_container, LV_ALIGN_TOP_MID, 0, 10);

    // “开始时间”按钮
    lv_obj_t* start_time_btn = lv_btn_create(time_container);
    lv_obj_set_size(start_time_btn, 120, 50);
    lv_obj_align(start_time_btn, LV_ALIGN_LEFT_MID, 10, 0);
    //lv_obj_set_name(start_time_btn, "Start Time");
    lv_obj_add_event_cb(start_time_btn, time_select_event_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t* start_label = lv_label_create(start_time_btn);
    lv_label_set_text(start_label, "开始时间");

    // “结束时间”按钮
    lv_obj_t* end_time_btn = lv_btn_create(time_container);
    lv_obj_set_size(end_time_btn, 120, 50);
    lv_obj_align(end_time_btn, LV_ALIGN_RIGHT_MID, -10, 0);
    //lv_obj_set_name(end_time_btn, "End Time");
    lv_obj_add_event_cb(end_time_btn, time_select_event_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t* end_label = lv_label_create(end_time_btn);
    lv_label_set_text(end_label, "结束时间");

    // 中间的“星期策略”按钮
    lv_obj_t* weekday_container = lv_obj_create(lv_scr_act());
    lv_obj_set_size(weekday_container, LV_HOR_RES, 60);
    lv_obj_align(weekday_container, LV_ALIGN_TOP_MID, 0, 80);

    lv_obj_t* weekday_btn = lv_btn_create(weekday_container);
    lv_obj_set_size(weekday_btn, 200, 50);
    lv_obj_align(weekday_btn, LV_ALIGN_CENTER, 0, 0);
    //lv_obj_set_name(weekday_btn, "Weekday Strategy");
    lv_obj_add_event_cb(weekday_btn, weekday_select_event_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t* weekday_label = lv_label_create(weekday_btn);
    lv_label_set_text(weekday_label, "星期策略");

    // 底部的滑动条
    lv_obj_t* slider = lv_slider_create(lv_scr_act());
    lv_obj_set_size(slider, 240, 20);
    lv_obj_align(slider, LV_ALIGN_BOTTOM_MID, 0, -20);
    lv_slider_set_range(slider, 0, 100);  // 设置滑动条的范围
    lv_slider_set_value(slider, 50, LV_ANIM_OFF);  // 设置滑动条初始值为50
}

static void generate_mask(lv_draw_buf_t* mask)
{
    /*Create a "8 bit alpha" canvas and clear it*/
    lv_obj_t* canvas = lv_canvas_create(lv_screen_active());
    lv_canvas_set_draw_buf(canvas, mask);
    lv_canvas_fill_bg(canvas, lv_color_white(), LV_OPA_TRANSP);

    lv_layer_t layer;
    lv_canvas_init_layer(canvas, &layer);

    /*Draw a label to the canvas. The result "image" will be used as mask*/
    lv_draw_rect_dsc_t rect_dsc;
    lv_draw_rect_dsc_init(&rect_dsc);
    rect_dsc.bg_grad.dir = LV_GRAD_DIR_VER;
    rect_dsc.bg_grad.stops[0].color = lv_color_black();
    rect_dsc.bg_grad.stops[1].color = lv_color_white();
    rect_dsc.bg_grad.stops[0].opa = LV_OPA_COVER;
    rect_dsc.bg_grad.stops[1].opa = LV_OPA_COVER;
    lv_area_t a = { 0, 0, mask->header.w - 1, mask->header.h / 2 - 10 };
    lv_draw_rect(&layer, &rect_dsc, &a);

    a.y1 = mask->header.h / 2 + 10;
    a.y2 = mask->header.h - 1;
    rect_dsc.bg_grad.stops[0].color = lv_color_white();
    rect_dsc.bg_grad.stops[1].color = lv_color_black();
    lv_draw_rect(&layer, &rect_dsc, &a);

    lv_canvas_finish_layer(canvas, &layer);

    /*Comment it to make the mask visible*/
    lv_obj_delete(canvas);
}
