// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

typedef struct schedule
{
    int8_t wday;
    int8_t hour_start;
    int8_t min_start;
    int8_t hour_end;
    int8_t min_end;
}schedule_t;

static void generate_mask(lv_draw_buf_t* mask);

static void time_select_event_cb(lv_event_t* e);
static void weekday_select_event_cb(lv_event_t* e);
static void time_picker_cancel_event_cb(lv_event_t* e);
static void weekday_picker_confirm_event_cb(lv_event_t* e);
static void weekday_picker_cancel_event_cb(lv_event_t* e);
static void time_picker_confirm_event_cb(lv_event_t* e);

static schedule_t schedule;
static lv_obj_t* weekbox[7];
static lv_obj_t* time_picker_dialog = NULL;
static lv_obj_t* weekday_picker_dialog = NULL;
static lv_obj_t* time_label_start = NULL;
static lv_obj_t* time_label_end = NULL;
static lv_obj_t* week_label = NULL;

// 时间选择回调函数
static void time_select_event_cb(lv_event_t* e) {

    int* where = lv_event_get_user_data(e);

    lv_obj_t* btn = lv_event_get_target(e);

    if (time_picker_dialog == NULL) {
    // 创建时间选择对话框
    time_picker_dialog = lv_obj_create(ui_stratDetail);
    lv_obj_set_size(time_picker_dialog, 240, 200);
    lv_obj_align(time_picker_dialog, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_bg_color(time_picker_dialog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(time_picker_dialog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 创建小时选择器
    static lv_style_t style;
    lv_style_init(&style);
    lv_style_set_size(&style, 90, 24);
    lv_style_set_bg_color(&style, lv_color_black());
    lv_style_set_text_color(&style, lv_color_white());
    lv_style_set_text_font(&style, &ui_font_Chinese16B);
    lv_style_set_border_width(&style, 0);
    lv_style_set_radius(&style, 0);

    ui_hourRoller = lv_roller_create(time_picker_dialog);
    lv_obj_add_style(ui_hourRoller, &style, 0);
    lv_obj_set_style_bg_opa(ui_hourRoller, LV_OPA_50, LV_PART_SELECTED);

    lv_roller_set_options(ui_hourRoller,
        "00\n"
        "01\n"
        "02\n"
        "03\n"
        "04\n"
        "05\n"
        "06\n"
        "07\n"
        "08\n"
        "09\n"
        "10\n"
        "11\n"
        "12\n"
        "13\n"
        "14\n"
        "15\n"
        "16\n"
        "17\n"
        "18\n"
        "19\n"
        "20\n"
        "21\n"
        "22\n"
        "23",
        LV_ROLLER_MODE_INFINITE);

    lv_obj_align(ui_hourRoller, LV_ALIGN_CENTER, -60, -60);
    lv_roller_set_visible_row_count(ui_hourRoller, 3);

    // 创建分钟选择器
    ui_minRoller = lv_roller_create(time_picker_dialog);
    lv_obj_add_style(ui_minRoller, &style, 0);
    lv_obj_set_style_bg_opa(ui_minRoller, LV_OPA_50, LV_PART_SELECTED);

    lv_roller_set_options(ui_minRoller,
        "00\n"
        "05\n"
        "10\n"
        "15\n"
        "20\n"
        "25\n"
        "30\n"
        "35\n"
        "40\n"
        "45\n"
        "50\n"
        "55",
        LV_ROLLER_MODE_INFINITE);
    lv_obj_align(ui_minRoller, LV_ALIGN_CENTER, 60, -60);
    lv_roller_set_visible_row_count(ui_minRoller, 3);

    /* Create the mask to make the top and bottom part of roller faded.
    * The width and height are empirical values for simplicity*/
//    int mask = 0;
//     LV_DRAW_BUF_DEFINE_STATIC(mask, 130, 150, LV_COLOR_FORMAT_L8);
//     LV_DRAW_BUF_INIT_STATIC(mask);

//     generate_mask(&mask);
//     lv_obj_set_style_bitmap_mask_src(ui_hourRoller, &mask, 0);
//     lv_obj_set_style_bitmap_mask_src(ui_minRoller, &mask, 0);

    // 创建“确定”和“取消”按钮
    lv_obj_t* btn_confirm = lv_btn_create(time_picker_dialog);
    lv_obj_align(btn_confirm, LV_ALIGN_BOTTOM_MID, -60, -10);
    lv_obj_t* label_confirm = lv_label_create(btn_confirm);
    lv_label_set_text(label_confirm, "确定");
    lv_obj_set_style_text_font(label_confirm, &ui_font_Chinese16B, LV_PART_MAIN);

    lv_obj_add_event_cb(btn_confirm, time_picker_confirm_event_cb, LV_EVENT_CLICKED, where);

    lv_obj_t* btn_cancel = lv_btn_create(time_picker_dialog);
    lv_obj_align(btn_cancel, LV_ALIGN_BOTTOM_MID, 60, -10);
    lv_obj_t* label_cancel = lv_label_create(btn_cancel);
    lv_label_set_text(label_cancel, "取消");
    lv_obj_set_style_text_font(label_cancel, &ui_font_Chinese16B, LV_PART_MAIN);

    lv_obj_add_event_cb(btn_cancel, time_picker_cancel_event_cb, LV_EVENT_CLICKED, NULL);
    }
}

// 时间选择确定回调
static void time_picker_confirm_event_cb(lv_event_t* e) {

    int where = lv_event_get_user_data(e);

    int hour = lv_roller_get_selected(ui_hourRoller);

    int minute = lv_roller_get_selected(ui_minRoller)*5;

    if (where)
    {
        lv_label_set_text_fmt(time_label_start, "%02d:%02d", hour, minute);
        schedule.hour_start = hour;
        schedule.min_start = minute;
    }
    else
    {
        lv_label_set_text_fmt(time_label_end, "%02d:%02d", hour, minute);
        schedule.hour_end = hour;
        schedule.min_end = minute;
    }
    lv_obj_del(time_picker_dialog);  // 关闭对话框
    time_picker_dialog = NULL;       // 清除对话框
}

// 时间选择取消回调
static void time_picker_cancel_event_cb(lv_event_t* e) {
    lv_obj_del(time_picker_dialog);  // 关闭对话框
    time_picker_dialog = NULL;       // 清除对话框
}

// 星期选择回调函数
static void weekday_select_event_cb(lv_event_t* e) {
    if (weekday_picker_dialog == NULL) {
        // 创建星期选择对话框
        weekday_picker_dialog = lv_obj_create(lv_scr_act());
        lv_obj_set_size(weekday_picker_dialog, 240, 200);
        lv_obj_align(weekday_picker_dialog, LV_ALIGN_CENTER, 0, 0);
        lv_obj_set_style_bg_color(weekday_picker_dialog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(weekday_picker_dialog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

        // 创建星期选择的复选框
        weekbox[1] = lv_checkbox_create(weekday_picker_dialog);
        lv_obj_align(weekbox[1], LV_ALIGN_TOP_LEFT, 10, 10);
        lv_checkbox_set_text(weekbox[1], "周一");
        lv_obj_set_style_text_color(weekbox[1], lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        lv_obj_set_style_text_font(weekbox[1], &ui_font_Chinese16B, LV_PART_MAIN);

        weekbox[2] = lv_checkbox_create(weekday_picker_dialog);
        lv_obj_align(weekbox[2], LV_ALIGN_TOP_LEFT, 10, 40);
        lv_checkbox_set_text(weekbox[2], "周二");
        lv_obj_set_style_text_color(weekbox[2], lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        lv_obj_set_style_text_font(weekbox[2], &ui_font_Chinese16B, LV_PART_MAIN);

        weekbox[3] = lv_checkbox_create(weekday_picker_dialog);
        lv_obj_align(weekbox[3], LV_ALIGN_TOP_LEFT, 10, 70);
        lv_checkbox_set_text(weekbox[3], "周三");
        lv_obj_set_style_text_color(weekbox[3], lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        lv_obj_set_style_text_font(weekbox[3], &ui_font_Chinese16B, LV_PART_MAIN);

        weekbox[4] = lv_checkbox_create(weekday_picker_dialog);
        lv_obj_align(weekbox[4], LV_ALIGN_TOP_LEFT, 10, 100);
        lv_checkbox_set_text(weekbox[4], "周四");
        lv_obj_set_style_text_color(weekbox[4], lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        lv_obj_set_style_text_font(weekbox[4], &ui_font_Chinese16B, LV_PART_MAIN);

        weekbox[5] = lv_checkbox_create(weekday_picker_dialog);
        lv_obj_align(weekbox[5], LV_ALIGN_TOP_LEFT, 150, 10);
        lv_checkbox_set_text(weekbox[5], "周五");
        lv_obj_set_style_text_color(weekbox[5], lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        lv_obj_set_style_text_font(weekbox[5], &ui_font_Chinese16B, LV_PART_MAIN);

        weekbox[6] = lv_checkbox_create(weekday_picker_dialog);
        lv_obj_align(weekbox[6], LV_ALIGN_TOP_LEFT, 150, 40);
        lv_checkbox_set_text(weekbox[6], "周六");
        lv_obj_set_style_text_color(weekbox[6], lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        lv_obj_set_style_text_font(weekbox[6], &ui_font_Chinese16B, LV_PART_MAIN);

        weekbox[0] = lv_checkbox_create(weekday_picker_dialog);
        lv_obj_align(weekbox[0], LV_ALIGN_TOP_LEFT, 150, 70);
        lv_checkbox_set_text(weekbox[0], "周日");
        lv_obj_set_style_text_color(weekbox[0], lv_color_hex(0xFFFFFF), LV_PART_MAIN);
        lv_obj_set_style_text_font(weekbox[0], &ui_font_Chinese16B, LV_PART_MAIN);

        // 创建“确定”和“取消”按钮
        lv_obj_t* btn_confirm = lv_btn_create(weekday_picker_dialog);
        lv_obj_align(btn_confirm, LV_ALIGN_BOTTOM_MID, -60, -10);
        lv_obj_t* label_confirm = lv_label_create(btn_confirm);
        lv_label_set_text(label_confirm, "确定");
        lv_obj_set_style_text_font(btn_confirm, &ui_font_Chinese16B, LV_PART_MAIN);

        lv_obj_add_event_cb(btn_confirm, weekday_picker_confirm_event_cb, LV_EVENT_CLICKED, NULL);

        lv_obj_t* btn_cancel = lv_btn_create(weekday_picker_dialog);
        lv_obj_align(btn_cancel, LV_ALIGN_BOTTOM_MID, 60, -10);
        lv_obj_t* label_cancel = lv_label_create(btn_cancel);
        lv_label_set_text(label_cancel, "取消");
        lv_obj_set_style_text_font(label_cancel, &ui_font_Chinese16B, LV_PART_MAIN);

        lv_obj_add_event_cb(btn_cancel, weekday_picker_cancel_event_cb, LV_EVENT_CLICKED, NULL);
    }
}

// 星期选择确定回调
static void weekday_picker_confirm_event_cb(lv_event_t* e) {
    char str[45] = { 0 };
    for (int i = 0;i < 7;i++)
    {
        if (lv_obj_has_state(weekbox[i], LV_STATE_CHECKED))
        {
            schedule.wday |= 1 << i;
            strcat(str, lv_checkbox_get_text(weekbox[i]));
        }
        else
            schedule.wday &= ~(1 << i);
    }
    
    lv_label_set_text(week_label,str);

    lv_obj_del(weekday_picker_dialog);  // 关闭对话框
    weekday_picker_dialog = NULL;       // 清除对话框
}

// 星期选择取消回调
static void weekday_picker_cancel_event_cb(lv_event_t* e) {
    lv_obj_del(weekday_picker_dialog);  // 关闭对话框
    weekday_picker_dialog = NULL;       // 清除对话框
}

void ui_stratDetail_screen_init(void)
{

    ui_stratDetail = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_stratDetail, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_stratDetail, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stratDetail, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // “开始时间”按钮
    lv_obj_t* start_time_btn = lv_btn_create(ui_stratDetail);
    lv_obj_set_size(start_time_btn, 80, 24);
    lv_obj_align(start_time_btn, LV_ALIGN_TOP_LEFT, 30, 30);
    lv_obj_add_event_cb(start_time_btn, time_select_event_cb, LV_EVENT_CLICKED, 1);
    lv_obj_t* start_label = lv_label_create(start_time_btn);
    lv_label_set_text(start_label, "开始时间");
    lv_obj_set_style_text_font(start_label, &ui_font_Chinese16B, LV_PART_MAIN);

    // “结束时间”按钮
    lv_obj_t* end_time_btn = lv_btn_create(ui_stratDetail);
    lv_obj_set_size(end_time_btn, 80, 24);
    lv_obj_align(end_time_btn, LV_ALIGN_TOP_RIGHT, -30, 30);
    lv_obj_add_event_cb(end_time_btn, time_select_event_cb, LV_EVENT_CLICKED, 0);
    lv_obj_t* end_label = lv_label_create(end_time_btn);
    lv_label_set_text(end_label, "结束时间");
    lv_obj_set_style_text_font(end_label, &ui_font_Chinese16B, LV_PART_MAIN);

    // 中间的“星期策略”按钮
    lv_obj_t* weekday_btn = lv_btn_create(ui_stratDetail);
    lv_obj_set_size(weekday_btn, 80, 24);
    lv_obj_align(weekday_btn, LV_ALIGN_CENTER, 0, 0);
    lv_obj_add_event_cb(weekday_btn, weekday_select_event_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_t* weekday_label = lv_label_create(weekday_btn);
    lv_label_set_text(weekday_label, "星期策略");
    lv_obj_set_style_text_font(weekday_label, &ui_font_Chinese16B, LV_PART_MAIN);

    time_label_start = lv_label_create(ui_stratDetail);
    lv_obj_align(time_label_start, LV_ALIGN_TOP_LEFT, 50, 58);
    lv_label_set_text(time_label_start, "--:--");
    lv_obj_set_style_text_color(time_label_start, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(time_label_start, &ui_font_Chinese16B, LV_PART_MAIN);

    time_label_end = lv_label_create(ui_stratDetail);
    lv_obj_align(time_label_end, LV_ALIGN_TOP_RIGHT, -50, 58);
    lv_label_set_text(time_label_end, "--:--");
    lv_obj_set_style_text_color(time_label_end, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(time_label_end, &ui_font_Chinese16B, LV_PART_MAIN);

    week_label = lv_label_create(ui_stratDetail);
    lv_obj_align(week_label, LV_ALIGN_CENTER, 0, 32);
    lv_label_set_text(week_label, "-");
    lv_obj_set_style_text_color(week_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(week_label, &ui_font_Chinese16B, LV_PART_MAIN);

    // 底部的滑动条
    lv_obj_t* slider = lv_slider_create(ui_stratDetail);
    lv_obj_set_size(slider, 220, 20);
    lv_obj_align(slider, LV_ALIGN_BOTTOM_MID, 0, -30);
    lv_slider_set_range(slider, 0, 100);  // 设置滑动条的范围
    lv_slider_set_value(slider, 50, LV_ANIM_OFF);  // 设置滑动条初始值为50

    lv_obj_add_event_cb(ui_stratDetail, ui_event_stratDetail, LV_EVENT_ALL, NULL);
}

static void generate_mask(lv_draw_buf_t* mask)
{
    /*Create a "8 bit alpha" canvas and clear it*/
    lv_obj_t* canvas = lv_canvas_create(lv_screen_active());
    lv_canvas_set_draw_buf(canvas, mask);
    lv_canvas_fill_bg(canvas, lv_color_white(), LV_OPA_TRANSP);

    lv_layer_t layer;
    lv_canvas_init_layer(canvas, &layer);

    /*Draw a label to the canvas. The result "image" will be used as mask*/
    lv_draw_rect_dsc_t rect_dsc;
    lv_draw_rect_dsc_init(&rect_dsc);
    rect_dsc.bg_grad.dir = LV_GRAD_DIR_VER;
    rect_dsc.bg_grad.stops[0].color = lv_color_black();
    rect_dsc.bg_grad.stops[1].color = lv_color_white();
    rect_dsc.bg_grad.stops[0].opa = LV_OPA_COVER;
    rect_dsc.bg_grad.stops[1].opa = LV_OPA_COVER;
    lv_area_t a = { 0, 0, mask->header.w - 1, mask->header.h / 2 - 10 };
    lv_draw_rect(&layer, &rect_dsc, &a);

    a.y1 = mask->header.h / 2 + 10;
    a.y2 = mask->header.h - 1;
    rect_dsc.bg_grad.stops[0].color = lv_color_white();
    rect_dsc.bg_grad.stops[1].color = lv_color_black();
    lv_draw_rect(&layer, &rect_dsc, &a);

    lv_canvas_finish_layer(canvas, &layer);

    /*Comment it to make the mask visible*/
    lv_obj_delete(canvas);
}
