// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_standby
void ui_standby_screen_init(void);
void ui_event_main(lv_event_t* e);
lv_obj_t* ui_standby;
lv_obj_t* ui_standby_dateLab;
lv_obj_t* ui_standby_timeLab;
lv_obj_t* ui_standby_welcomeLab;

//SCEEN:ui_status
void ui_status_screen_init(void);
void ui_event_status_return(lv_event_t* e);
void ui_event_status(lv_event_t* e);
lv_obj_t* ui_status;
lv_obj_t* cur_act;
lv_obj_t* ui_status_wifiBtn;
lv_obj_t* ui_status_blueToothBtn;
lv_obj_t* ui_statusSlider;

// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_control(lv_event_t* e);
lv_obj_t* hour_hand;
lv_obj_t* minute_hand;
lv_obj_t* second_hand;
lv_obj_t *ui_main;
lv_obj_t* ui_dateLab;
lv_obj_t* ui_timeLab;
lv_obj_t* ui_tempBar;
lv_obj_t* ui_waterLevelBar;
lv_obj_t* ui_mainInfo;
lv_obj_t* ui_mainInfoLab;

// CUSTOM VARIABLES

//SCREEN:ui_QR
void ui_QR_screen_init(void);
lv_obj_t* ui_QR;

// SCREEN: ui_control
void ui_control_screen_init(void);
bool flag = false;
lv_obj_t* ui_control;
lv_obj_t* ui_controlList;

// SCREEN: ui_more
void ui_more_screen_init(void);
void ui_event_more(lv_event_t* e);
lv_obj_t* ui_more;
lv_obj_t* ui_moreList;
uint8_t more_flag;

// SCREEN: ui_temp
void ui_temp_screen_init(void);
lv_obj_t* ui_temp;
lv_obj_t* ui_tempLab;
lv_obj_t* ui_temp_ave_Lab;
lv_obj_t* ui_tempChart;
lv_obj_t* ui_tempSeries;
lv_obj_t* ui_tempChart_Yaxis;


// SCREEN: ui_waterLevel
void ui_waterLevel_screen_init(void);
void ui_event_waterLevel(lv_event_t* e);
lv_obj_t* ui_waterLevel;
lv_obj_t* ui_waterLevelLab;


// SCREEN: ui_light
int lightMode = 0;
const char *lightModeArr[6] = {"氛围","观影","浪漫","星空","日常","关闭"};
void ui_light_screen_init(void);
void ui_event_light( lv_event_t * e);
lv_obj_t *ui_light;
void ui_event_lightPer( lv_event_t * e);
lv_obj_t *ui_lightPer;
lv_obj_t* ui_lightinPer;
lv_obj_t *ui_setLightPerLab;
lv_obj_t *ui_curLightPerLab;
void ui_event_addlightPer( lv_event_t * e);
lv_obj_t *ui_addlightPer;
lv_obj_t *ui_addlightPerLab;
void ui_event_diflightPer( lv_event_t * e);
lv_obj_t *ui_diflightPer;
lv_obj_t *ui_diflightPerLab;
void ui_event_lightStatus(lv_event_t* e);
lv_obj_t *ui_lightStatus;
lv_obj_t *ui_lightStatusLab;
lv_obj_t *ui_lightStatusBtn;
lv_obj_t *ui_lightStatusImg;
lv_obj_t *ui_lightMode;
lv_obj_t *ui_lightModeLab;
void ui_event_atmosphereBtn( lv_event_t * e);
lv_obj_t *ui_atmosphereBtn;
lv_obj_t *ui_atmosphereBtnLab;
void ui_event_MovieBtn( lv_event_t * e);
lv_obj_t *ui_MovieBtn;
lv_obj_t *ui_MovieBtnLab;
void ui_event_romanBtn( lv_event_t * e);
lv_obj_t *ui_romanBtn;
lv_obj_t *ui_romanBtnLab;
void ui_event_starryBtn( lv_event_t * e);
lv_obj_t *ui_starryBtn;
lv_obj_t *ui_starryBtnLab;
void ui_event_dailyBtn( lv_event_t * e);
lv_obj_t *ui_dailyBtn;
lv_obj_t *ui_dailyBtnLab;
// CUSTOM VARIABLES


// SCREEN: ui_pump
void ui_pump_screen_init(void);
lv_obj_t *ui_pump;
void ui_event_pumpPer( lv_event_t * e);
lv_obj_t *ui_pumpPer;
lv_obj_t* ui_pumpinPer;
lv_obj_t *ui_curpumpPerLab;
lv_obj_t *ui_setpumpPerLab;
void ui_event_addpumpPer( lv_event_t * e);
lv_obj_t *ui_addpumpPer;
lv_obj_t *ui_addpumpPerLab;
void ui_event_difpumpPer( lv_event_t * e);
lv_obj_t *ui_difpumpPer;
lv_obj_t *ui_difpumpPerLab;
lv_obj_t *ui_pumpStatus;
lv_obj_t *ui_pumpStatusLab;
lv_obj_t *ui_pumpStatusBtn;
lv_obj_t *ui_pumpStatusImg;
// CUSTOM VARIABLES


// SCREEN: ui_heater
void ui_heater_screen_init(void);
void ui_event_heater( lv_event_t * e);
lv_obj_t *ui_heater;
void ui_event_heaterPer( lv_event_t * e);
lv_obj_t *ui_heaterPer;
lv_obj_t* ui_heaterinPer;
lv_obj_t *ui_curheaterPerLab;
lv_obj_t *ui_setheaterPerLab;
void ui_event_addheaterPer( lv_event_t * e);
lv_obj_t *ui_addheaterPer;
lv_obj_t *ui_addheaterPerLab;
void ui_event_difheaterPer( lv_event_t * e);
lv_obj_t *ui_difheaterPer;
lv_obj_t *ui_difheaterPerLab;
lv_obj_t *ui_heaterStatus;
lv_obj_t *ui_heaterStatusLab;
lv_obj_t *ui_heaterStatusBtn;
lv_obj_t *ui_heaterStatusImg;
// CUSTOM VARIABLES


// SCREEN: ui_aroma
void ui_aroma_screen_init(void);
void ui_event_aroma( lv_event_t * e);
lv_obj_t *ui_aroma;
void ui_event_aromaPer( lv_event_t * e);
lv_obj_t *ui_aromaPer;
lv_obj_t* ui_aromainPer;
lv_obj_t *ui_curaromaPerLab;
lv_obj_t *ui_setaromaPerLab;
void ui_event_addaromaPer( lv_event_t * e);
lv_obj_t *ui_addaromaPer;
lv_obj_t *ui_addaromaPerLab;
void ui_event_difaromaPer( lv_event_t * e);
lv_obj_t *ui_difaromaPer;
lv_obj_t *ui_difaromaPerLab;
lv_obj_t *ui_aromaStatus;
lv_obj_t *ui_aromaStatusLab;
lv_obj_t *ui_aromaStatusBtn;
lv_obj_t *ui_aromaStatusImg;
// CUSTOM VARIABLES


// SCREEN: ui_feed
void ui_feed_screen_init(void);
void ui_event_feed( lv_event_t * e);
lv_obj_t *ui_feed;
void ui_event_feedPer( lv_event_t * e);
lv_obj_t *ui_feedPer;
lv_obj_t* ui_feedinPer;
lv_obj_t *ui_curfeedPerLab;
lv_obj_t *ui_setfeedPerLab;
void ui_event_addfeedPer( lv_event_t * e);
lv_obj_t *ui_addfeedPer;
lv_obj_t *ui_addfeedPerLab;
void ui_event_diffeedPer( lv_event_t * e);
lv_obj_t *ui_diffeedPer;
lv_obj_t *ui_diffeedPerLab;
lv_obj_t *ui_feedStatus;
lv_obj_t *ui_feedStatusLab;
lv_obj_t *ui_feedStatusBtn;
lv_obj_t *ui_feedStatusImg;
lv_obj_t *ui_feedAmount;
lv_obj_t *ui_feedAmountLab;
lv_obj_t *ui_feedAmountSlider;
lv_obj_t *ui_feedAmountSliderLab;
lv_obj_t *ui_feedFreq;
lv_obj_t *ui_feedFreqLab;
lv_obj_t *ui_feedFreqBtn;
lv_obj_t *ui_oneADayBtn;
lv_obj_t *ui_oneADayBtnLab;
lv_obj_t *ui_twoADayBtn;
lv_obj_t *ui_twoADayBtnLab;
lv_obj_t *ui_threeADayBtn;
lv_obj_t *ui_threeADayBtnLab;
lv_obj_t *ui_fiveAWeekBtn;
lv_obj_t *ui_fiveAWeekBtnLab;
lv_obj_t *ui_sevenAWeekBtn;
lv_obj_t *ui_sevenAWeekBtnLab;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
//    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

//设置背景
void set_background(lv_obj_t* scr) {
    lv_obj_t* ui_backgroundImg = lv_img_create(scr);
    lv_image_set_src(ui_backgroundImg, &ui_img_main_png);
    lv_obj_set_width(ui_backgroundImg, LV_SIZE_CONTENT);   /// 889
    lv_obj_set_height(ui_backgroundImg, LV_SIZE_CONTENT);    /// 500
    lv_obj_set_align(ui_backgroundImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgroundImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backgroundImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
}

void ui_event_status_return(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        _ui_screen_change(&cur_act, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, NULL);
    }
}

void ui_event_status(lv_event_t* e)
{
    static lv_point_t touch_start_pos;
    static bool is_touch_down = false;

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        cur_act = lv_event_get_current_target_obj(e);
        _ui_screen_change(&ui_status, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_status_screen_init);
    }

    //if (event_code == LV_EVENT_CLICKED)
    //{
    //    lv_obj_t* obj = lv_event_get_target(e);
    //    lv_indev_t* indev = lv_event_get_indev(e);
    //    lv_point_t p;

    //    lv_indev_get_point(indev, &p);

    //    touch_start_pos.x = p.x;
    //    touch_start_pos.y = p.y;
    //    is_touch_down = true;
    //}

    //
    //if (event_code == LV_EVENT_PRESSING)
    //{
    //    if (!is_touch_down) return;

    //    lv_obj_t* obj = lv_event_get_target(e);
    //    lv_indev_t* indev = lv_event_get_indev(e);
    //    lv_point_t p;

    //    lv_indev_get_point(indev, &p);

    //    touch_start_pos.x = p.x;
    //    touch_start_pos.y = p.y;
    //    lv_indev_get_point(indev, &p);

    //    /* 判断是否从屏幕顶部下拉 */
    //    if (touch_start_pos.y <= 20 &&  /* 顶部区域，可以根据需要调整 */
    //        p.y > touch_start_pos.y &&                   /* 向下拉 */
    //        p.y - touch_start_pos.y > 40) { /* 拉下的距离，可以根据需要调整 */

    //        /* 触发事件 */
    //        is_touch_down = false;
    //        cur_act = lv_event_get_user_data(e);
    //        _ui_screen_change(&ui_status, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_status_screen_init);
    //    }
    //}
    //if (event_code == LV_EVENT_PRESS_LOST)
    //    is_touch_down = false;
}

//主页界面
void ui_event_main(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE  && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_main_screen_init);
        flag = false;
    }
}

//小程序<=主页=>温度界面
void ui_event_temp(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        _ui_screen_change(&ui_QR, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_QR_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        _ui_screen_change(&ui_temp, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_temp_screen_init);
    }
}

//控制界面
void ui_event_control(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_control_screen_init);
    }
}

//温度界面
void ui_event_tempBtn(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_temp, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_temp_screen_init);
    }
}

//水位界面
void ui_event_waterLevelBtn(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_waterLevel, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_waterLevel_screen_init);
    }
}

//灯光界面
void ui_event_lighterBtn( lv_event_t * e) {

    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
    flag = true;
    _ui_screen_change( &ui_light, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_light_screen_init);
}
}

//加热器界面
void ui_event_heaterBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
    flag = true;
    _ui_screen_change( &ui_heater, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_heater_screen_init);
}
}

//水泵界面
void ui_event_waterPumpBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
    flag = true;
    _ui_screen_change( &ui_pump, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_pump_screen_init);
}
}

//更多界面
void ui_event_moreBtn(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_more, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_more_screen_init);
    }
}

void ui_event_more(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_control_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
       _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_control_screen_init);
    }
}

//香薰界面
void ui_event_AromatherapyBtn(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_aroma, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_aroma_screen_init);
    }
}

//喂食器界面
void ui_event_feederBtn(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_feed, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_feed_screen_init);
    }
}

//主页<=温度=>水位界面
void ui_event_waterLevel(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_main_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_waterLevel, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_waterLevel_screen_init);
    }
}

//温度<=水位=>水泵界面
void ui_event_waterPump(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_temp, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_temp_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_pump, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_pump_screen_init);
        }
}

//水位<=水泵=>灯光界面
void ui_event_light(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_waterLevel, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_waterLevel_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_light, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_light_screen_init);
    }
}

//水泵<=灯光=>##界面
void ui_event_next(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_pump, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_pump_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_pump, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_pump_screen_init);
    }
}

//灯光亮度显示
void ui_event_lightPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_curLightPerLab, target, "", "%");
}
}

//灯光亮度增加
void ui_event_addlightPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED && lightMode < UI_THEME_OFF) {
      _ui_arc_increment( ui_lightPer, 1);
}
}

//灯光亮度降低
void ui_event_diflightPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED && lightMode <UI_THEME_OFF) {
      _ui_arc_increment( ui_lightPer, -1);
}
}

//灯光状态切换
void ui_event_lightStatus(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED) {
        if (lightMode < UI_THEME_OFF) {
            _ui_switch_theme(UI_THEME_OFF);
            lv_obj_remove_flag(ui_lightPer, LV_OBJ_FLAG_CLICKABLE);
            lv_label_set_text(ui_curLightPerLab, "关闭");
            lightMode += UI_THEME_OFF;
        }
        else{
            lightMode -= UI_THEME_OFF;
            _ui_switch_theme(lightMode);
            lv_obj_add_flag(ui_lightPer, LV_OBJ_FLAG_CLICKABLE);
            _ui_arc_set_text_value(ui_curLightPerLab, ui_lightPer, "", "%");
        }
    }
}
//灯光模式氛围
void ui_event_atmosphereBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if ( event_code == LV_EVENT_CLICKED && lightMode <=UI_THEME_OFF) {
          lightMode = UI_THEME_ATMO;
          _ui_switch_theme( UI_THEME_ATMO );
    }
}

//灯光模式观影
void ui_event_MovieBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED && lightMode <= UI_THEME_OFF) {
      lightMode = UI_THEME_MOVIE;
      _ui_switch_theme( UI_THEME_MOVIE );
}
}

//灯光模式浪漫
void ui_event_romanBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED && lightMode <= UI_THEME_OFF){
      lightMode = UI_THEME_ROMAN;
      _ui_switch_theme( UI_THEME_ROMAN );
}
}

//灯光模式星空
void ui_event_starryBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED && lightMode <= UI_THEME_OFF) {
      lightMode = UI_THEME_STARRY;
      _ui_switch_theme( UI_THEME_STARRY );
}
}

//灯光模式日常
void ui_event_dailyBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED && lightMode <= UI_THEME_OFF) {
      lightMode = UI_THEME_DAILY;
      _ui_switch_theme( UI_THEME_DAILY );
}
}

//水泵状态切换
void ui_event_pumpStatus(lv_event_t* e)
{
    static lightMode=1;
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED) {
        if (lightMode) {
            lv_obj_set_style_arc_color(ui_pumpPer, lv_color_hex(BTNCLO), LV_PART_INDICATOR | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_color(ui_pumpStatusBtn, lv_color_hex(0x007AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_remove_flag(ui_pumpPer, LV_OBJ_FLAG_CLICKABLE);
            lv_label_set_text(ui_curpumpPerLab, "关闭");
            lightMode=!lightMode;
        }
        else {
            lightMode = !lightMode;
            _ui_switch_theme(lightMode);
            lv_obj_add_flag(ui_pumpPer, LV_OBJ_FLAG_CLICKABLE);
            _ui_arc_set_text_value(ui_curLightPerLab, ui_pumpPer, "", "%");
        }
    }
}

//水泵档位显示
void ui_event_pumpPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_curpumpPerLab, target, "", "");
}
}

//水泵档位提高
void ui_event_addpumpPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_increment( ui_pumpPer, 1);
}
}

//水泵档位降低
void ui_event_difpumpPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_increment( ui_pumpPer, -1);
}
}

//加热棒返回主界面
void ui_event_heater( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_main_screen_init);
}
}

//加热棒温度显示
void ui_event_heaterPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_curheaterPerLab, target, "", "");
      _ui_arc_set_text_value( ui_heaterStatusLab, target, "运行中 | 温度", "℃");
}
}

//加热棒温度提高
void ui_event_addheaterPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_increment( ui_heaterPer, 1);
}
}

//加热棒温度降低
void ui_event_difheaterPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_increment(ui_heaterPer, -1);
}
}

//香薰强度显示
void ui_event_aroma( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_main_screen_init);
}
}

//香薰强度显示
void ui_event_aromaPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_curaromaPerLab, target, "", "");
}
}

//香薰强度提高
void ui_event_addaromaPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_increment( ui_aromaPer, 1);
}
}
//香薰强度降低
void ui_event_difaromaPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_increment( ui_aromaPer, -1);
}
}

//喂食界面跳转
void ui_event_feed( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_main_screen_init);
}
}

//喂食量标签显示 
void ui_event_feedPer(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t* target = lv_event_get_target(e);

    if (event_code == LV_EVENT_VALUE_CHANGED) {

        int uniDig = (int)lv_arc_get_value(target) % 10, tenDig = (int)lv_arc_get_value(target) / 10;
        char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];

        lv_snprintf(buf, sizeof(buf), "%d%s%d%s", (int)tenDig, ".", uniDig, "h");

        lv_label_set_text(ui_curfeedPerLab, buf);
    }
}
//喂食量增加
void ui_event_addfeedPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_increment( ui_feedPer, 1);
}
}

//喂食量减少
void ui_event_diffeedPer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_arc_increment( ui_feedPer, -1);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);

ui_standby_screen_init();
ui_main_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_standby);
}
