// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_standby
void ui_standby_screen_init(void);
void ui_event_main(lv_event_t* e);
lv_obj_t* ui_standby;
lv_obj_t* ui_standby_dateLab;
lv_obj_t* ui_standby_timeLab;
lv_obj_t* ui_standby_welcomeLab;

//SCEEN:ui_status
void ui_status_screen_init(void);
void ui_event_status_return(lv_event_t* e);
void ui_event_status(lv_event_t* e);
lv_obj_t* ui_status;
lv_obj_t* cur_act;
lv_obj_t* ui_status_wifiBtn;
lv_obj_t* ui_status_blueToothBtn;
lv_obj_t* ui_statusSlider;

// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_control(lv_event_t* e);
lv_obj_t* hour_hand;
lv_obj_t* minute_hand;
lv_obj_t* second_hand;
lv_obj_t *ui_main;
lv_obj_t* ui_dateLab;
lv_obj_t* ui_timeLab;
lv_obj_t* ui_tempBar;
lv_obj_t* ui_waterLevelBar;
lv_obj_t* ui_mainInfo;
lv_obj_t* ui_mainInfoLab;

// CUSTOM VARIABLES

//SCREEN:ui_QR
void ui_QR_screen_init(void);
void ui_event_QR(lv_event_t* e);
lv_obj_t* ui_QR;

// SCREEN: ui_control
void ui_control_screen_init(void);
bool flag = false;      //where is the screen from? control(true) or main(false)
lv_obj_t* ui_control;
lv_obj_t* ui_controlList;

// SCREEN: ui_more
void ui_more_screen_init(void);
void ui_event_more(lv_event_t* e);
lv_obj_t* ui_more;
lv_obj_t* ui_moreList;

// SCREEN: ui_temp
void ui_temp_screen_init(void);
lv_obj_t* ui_temp;
lv_obj_t* ui_tempLab;
lv_obj_t* ui_temp_ave_Lab;
lv_obj_t* ui_tempChart;
lv_obj_t* ui_tempSeries;
lv_obj_t* ui_tempChart_Yaxis;


// SCREEN: ui_waterLevel
void ui_waterLevel_screen_init(void);
void ui_event_waterLevel(lv_event_t* e);
lv_obj_t* ui_waterLevel;
lv_obj_t* ui_waterLevelLab;

// SCREEN: ui_strat
enum ui_strat_mode_t ui_strat_mode;
unsigned int ui_strat_mode_enable_mask = 1 << 0 | 1 << 1;
// CUSTOM VARIABLES

// SCREEN: ui_strat_detail
lv_obj_t* ui_stratDetail;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
//    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

//设置背景
void set_background(lv_obj_t* scr) {
    lv_obj_t* ui_backgroundImg = lv_img_create(scr);
    lv_image_set_src(ui_backgroundImg, &ui_img_main_png);
    lv_obj_set_width(ui_backgroundImg, LV_SIZE_CONTENT);   /// 889
    lv_obj_set_height(ui_backgroundImg, LV_SIZE_CONTENT);    /// 500
    lv_obj_set_align(ui_backgroundImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgroundImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backgroundImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
}

void ui_event_status_return(lv_event_t* e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        _ui_screen_change(&cur_act, LV_SCR_LOAD_ANIM_OUT_TOP, 500, 0, NULL);
    }
}

void ui_event_status(lv_event_t* e)
{
    static lv_point_t touch_start_pos;
    static bool is_touch_down = false;

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        cur_act = lv_event_get_current_target_obj(e);
        _ui_screen_change(&ui_status, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_status_screen_init);
    }

    //if (event_code == LV_EVENT_CLICKED)
    //{
    //    lv_obj_t* obj = lv_event_get_target(e);
    //    lv_indev_t* indev = lv_event_get_indev(e);
    //    lv_point_t p;

    //    lv_indev_get_point(indev, &p);

    //    touch_start_pos.x = p.x;
    //    touch_start_pos.y = p.y;
    //    is_touch_down = true;
    //}

    //
    //if (event_code == LV_EVENT_PRESSING)
    //{
    //    if (!is_touch_down) return;

    //    lv_obj_t* obj = lv_event_get_target(e);
    //    lv_indev_t* indev = lv_event_get_indev(e);
    //    lv_point_t p;

    //    lv_indev_get_point(indev, &p);

    //    touch_start_pos.x = p.x;
    //    touch_start_pos.y = p.y;
    //    lv_indev_get_point(indev, &p);

    //    /* 判断是否从屏幕顶部下拉 */
    //    if (touch_start_pos.y <= 20 &&  /* 顶部区域，可以根据需要调整 */
    //        p.y > touch_start_pos.y &&                   /* 向下拉 */
    //        p.y - touch_start_pos.y > 40) { /* 拉下的距离，可以根据需要调整 */

    //        /* 触发事件 */
    //        is_touch_down = false;
    //        cur_act = lv_event_get_user_data(e);
    //        _ui_screen_change(&ui_status, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_status_screen_init);
    //    }
    //}
    //if (event_code == LV_EVENT_PRESS_LOST)
    //    is_touch_down = false;
}

//主页界面
void ui_event_main(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE  && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_OUT_TOP, 500, 0, &ui_main_screen_init);
        flag = false;
    }

}

//小程序<=主页=>温度界面
void ui_event_temp(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        _ui_screen_change(&ui_QR, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_QR_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        _ui_screen_change(&ui_temp, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_temp_screen_init);
    }
}

//控制界面
void ui_event_control(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_control_screen_init);
    }
}

//温度界面
void ui_event_tempBtn(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_temp, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_temp_screen_init);
    }
}

//水位界面
void ui_event_waterLevelBtn(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_waterLevel, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_waterLevel_screen_init);
    }
}

//灯光界面
void ui_event_lighterBtn( lv_event_t * e) {

    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
    flag = true;
    ui_strat_screen_entry(ui_strat_mode_light, LV_SCR_LOAD_ANIM_OVER_LEFT);
}
}

//加热器界面
void ui_event_heaterBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
    flag = true;
    ui_strat_screen_entry(ui_strat_mode_heat, LV_SCR_LOAD_ANIM_OVER_LEFT);
}
}

//水泵界面
void ui_event_waterPumpBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
    flag = true;
    ui_strat_screen_entry(ui_strat_mode_pump, LV_SCR_LOAD_ANIM_OVER_LEFT);
}
}

//更多界面
void ui_event_moreBtn(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_more, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_more_screen_init);
    }
}

//二维码=>主页界面
void ui_event_QR(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_main_screen_init);
    }
}

//控制<=更多=>控制
void ui_event_more(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_control_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
       _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_control_screen_init);
    }
}

//香薰界面
void ui_event_AromatherapyBtn(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        ui_strat_screen_entry(ui_strat_mode_aroma, LV_SCR_LOAD_ANIM_OVER_LEFT);
    }
}

//喂食器界面
void ui_event_feederBtn(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        ui_strat_screen_entry(ui_strat_mode_feed, LV_SCR_LOAD_ANIM_OVER_LEFT);
    }
}

//杀菌灯界面
void ui_event_sanitizerBtn(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        ui_strat_screen_entry(ui_strat_mode_sanit, LV_SCR_LOAD_ANIM_OVER_LEFT);
    }
}

//蛋白质分解器界面
void ui_event_isolatorBtn(lv_event_t* e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        flag = true;
        ui_strat_screen_entry(ui_strat_mode_isola, LV_SCR_LOAD_ANIM_OVER_LEFT);
    }
}

//主页<=温度=>水位界面
void ui_event_waterLevel(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_main_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_waterLevel, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_waterLevel_screen_init);
    }
}

//温度<=水位=>灯光策略界面
void ui_event_waterPump(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            _ui_screen_change(&ui_temp, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_temp_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
            ui_strat_screen_entry(ui_strat_mode_light, LV_SCR_LOAD_ANIM_MOVE_LEFT);
        }
}

//水位<=灯光策略<=>水泵策略<=>...=>主界面
void ui_event_strat(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
        {
            do {
                if (ui_strat_mode == 1)
                {
                    _ui_screen_change(&ui_waterLevel, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_waterLevel_screen_init);
                    break;
                }
                ui_strat_mode = ui_strat_mode >> 1;
                if (ui_strat_mode & ui_strat_mode_enable_mask)
                {
                    ui_strat_screen_entry(ui_strat_mode, LV_SCR_LOAD_ANIM_MOVE_RIGHT);
                    break;
                }
            } while (1);
        }
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        if (flag)
        {
            _ui_screen_change(&ui_control, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_control_screen_init);
            flag = !flag;
        }
        else
        {
            do {
                if ((ui_strat_mode << 1) & ui_strat_mode_max)
                {
                    _ui_screen_change(&ui_main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_main_screen_init);
                    break;
                }
                ui_strat_mode = ui_strat_mode << 1;
                if (ui_strat_mode & ui_strat_mode_enable_mask)
                {
                    ui_strat_screen_entry(ui_strat_mode, LV_SCR_LOAD_ANIM_MOVE_LEFT);
                    break;
                }
            } while (1);
        }
    }
}

//具体策略界面=>返回策略界面
void ui_event_stratDetail(lv_event_t* e) {

    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        ui_strat_screen_entry(ui_strat_mode, LV_SCR_LOAD_ANIM_OUT_BOTTOM);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        ui_strat_screen_entry(ui_strat_mode, LV_SCR_LOAD_ANIM_OUT_BOTTOM);
    }
}


///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);

ui_standby_screen_init();
ui_main_screen_init();
ui_strat_screen_init();
ui_stratDetail_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_standby);
}
