// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <math.h>
#include "lvgl.h"
#include <time.h>
#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

/*********************
 *      DEFINES
 *********************/
#define TEMP    25
#define WL      "正常"
#define PUMP    7
#define LANDE 0x0A9AF7

// SCREEN: ui_standby
void ui_standby_screen_init(void);
void ui_event_main(lv_event_t* e);
extern lv_obj_t* ui_standby;
extern lv_obj_t* ui_standby_dateLab;
extern lv_obj_t* ui_standby_timeLab;
extern lv_obj_t* ui_standby_welcomeLab;

//SCEEN:ui_status
void ui_status_screen_init(void);
void ui_event_status_return(lv_event_t* e);
void ui_event_status(lv_event_t* e);
extern lv_obj_t* ui_status;
extern lv_obj_t* cur_act;
extern lv_obj_t* ui_status_wifiBtn;
extern lv_obj_t* ui_status_blueToothBtn;
extern lv_obj_t* ui_statusSlider;


// SCREEN: ui_main
void ui_main_screen_init(void);
void ui_event_control(lv_event_t* e);
extern lv_obj_t* hour_hand;
extern lv_obj_t* minute_hand;
extern lv_obj_t* second_hand;
extern lv_obj_t* ui_main;
extern lv_obj_t* ui_dateLab;
extern lv_obj_t* ui_timeLab;
extern lv_obj_t* ui_tempBar;
extern lv_obj_t* ui_waterLevelBar;
extern lv_obj_t* ui_mainInfo;
extern lv_obj_t* ui_mainInfoLab;


// CUSTOM VARIABLES

//SCREEN:ui_QR
void ui_QR_screen_init(void);
void ui_event_QR(lv_event_t* e);
extern lv_obj_t* ui_QR;

// SCREEN: ui_control
void ui_control_screen_init(void);
void ui_event_tempBtn(lv_event_t* e);
void ui_event_waterLevelBtn(lv_event_t* e);
void ui_event_lighterBtn(lv_event_t* e);
void ui_event_heaterBtn(lv_event_t* e);
void ui_event_waterPumpBtn(lv_event_t* e);
void ui_event_moreBtn(lv_event_t* e);
void ui_event_AromatherapyBtn(lv_event_t* e);
void ui_event_feederBtn(lv_event_t* e);
void ui_event_sanitizerBtn(lv_event_t* e);
void ui_event_isolatorBtn(lv_event_t* e);
extern lv_obj_t* ui_control;
extern lv_obj_t* ui_controlList;

// SCREEN: ui_more
void ui_more_screen_init(void);
void ui_event_more(lv_event_t* e);
extern lv_obj_t* ui_more;
extern lv_obj_t* ui_moreList;

// SCREEN: ui_temp
void ui_temp_screen_init(void);
void ui_event_temp(lv_event_t* e);
extern lv_obj_t* ui_temp;
extern lv_obj_t* ui_tempLab;
extern lv_obj_t* ui_temp_ave_Lab;
extern lv_obj_t* ui_tempChart;
extern lv_obj_t* ui_tempChart_Yaxis;
extern lv_obj_t* ui_tempSeries;

// SCREEN: ui_waterLevel
void ui_waterLevel_screen_init(void);

void ui_event_waterLevel(lv_event_t* e);
void ui_event_waterPump(lv_event_t* e);
extern lv_obj_t* ui_waterLevel;
extern lv_obj_t* ui_waterLevelLab;

// SCREEN: ui_strat
enum ui_strat_mode_t {
    ui_strat_mode_light = 1 << 0,
    ui_strat_mode_pump = 1 << 1,
    ui_strat_mode_heat = 1 << 2,
    ui_strat_mode_feed = 1 << 3,
    ui_strat_mode_aroma = 1 << 4,
    ui_strat_mode_sanit = 1 << 5,
    ui_strat_mode_isola = 1 << 6,
    ui_strat_mode_max = 1 << 7,
};
extern unsigned int ui_strat_mode_enable_mask;
extern enum ui_strat_mode_t ui_strat_mode;
void ui_strat_screen_init();
void ui_strat_screen_entry(enum ui_strat_mode_t ui_strat_mode, lv_screen_load_anim_t anim);
void ui_event_strat(lv_event_t* e);
// CUSTOM VARIABLES

// SCREEN: ui_strat_detail
extern lv_obj_t* ui_stratDetail;
void ui_stratDetail_screen_init();
void ui_event_stratDetail(lv_event_t* e);
extern lv_obj_t* ui_hourRoller;
extern lv_obj_t* ui_minRoller;
extern lv_obj_t* ui_wdayRoller;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_main_png);
LV_IMG_DECLARE( ui_img_setup_png);   // assets/setup.png
LV_IMG_DECLARE( ui_img_light_png);   // assets/light.png
LV_IMG_DECLARE( ui_img_heater_png);   // assets/heater.png
LV_IMG_DECLARE( ui_img_pump_png);   // assets/pump.png
LV_IMG_DECLARE( ui_img_feed_png);   // assets/feed.png
LV_IMG_DECLARE( ui_img_level_png);   // assets/level.png
LV_IMG_DECLARE( ui_img_aroma_png);   // assets/aroma.png
LV_IMG_DECLARE(ui_img_decom_png);   // assets/decom.png
LV_IMG_DECLARE( ui_img_uv_png);   // assets/lamp.png
LV_IMG_DECLARE( ui_img_off_png);   // assets/off.png
LV_IMG_DECLARE(ui_img_temp_png);   // assets/temp.png
LV_IMG_DECLARE(ui_img_bright_png);   // assets/bright.png
LV_IMG_DECLARE(ui_img_more_png);   // assets/more.png
LV_IMG_DECLARE(ui_img_lightboard_png);
LV_IMG_DECLARE(ui_img_pump_fan_png);
LV_IMG_DECLARE(ui_img_pump_shell_png);



// FONTS
//LV_FONT_DECLARE( ui_font_Chinese10);
//LV_FONT_DECLARE( ui_font_Chinese12);
//LV_FONT_DECLARE( ui_font_Chinese14);
//LV_FONT_DECLARE( ui_font_Chinese16);
LV_FONT_DECLARE( ui_font_Chinese16B);
LV_FONT_DECLARE( ui_font_Chinese32B);
//LV_FONT_DECLARE(ui_font_Chinese32);
//LV_FONT_DECLARE( ui_font_Chinese8);
//LV_FONT_DECLARE(ui_font_Chinese44);
//LV_FONT_DECLARE(ui_font_Chinese64);
LV_FONT_DECLARE(ui_font_Chinese96);
// UI INIT
void ui_init(void);
void set_background(lv_obj_t* scr);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
