// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

//Arc的主题色彩设置
const ui_theme_variable_t _ui_theme_color_exarc[6]            = { ATMO, MOVIE, ROMAN, STARRY, DAILY, 0xffffff};
const ui_theme_variable_t _ui_theme_alpha_exarc[6]            = { ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, 0};
const ui_theme_variable_t _ui_theme_color_inarc[6]            = { ATMO, MOVIE, ROMAN, STARRY, DAILY };
const ui_theme_variable_t _ui_theme_alpha_inarc[6]            = { ALPHA/8, ALPHA/8, ALPHA/8, ALPHA/8, ALPHA/8, 0 };

const ui_theme_variable_t _ui_theme_color_offbtn[6]            = { ATMO, MOVIE, ROMAN, STARRY, DAILY ,OFFBTN};
const ui_theme_variable_t _ui_theme_alpha_offbtn[6]            = { ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA };

//按钮的主题色彩设置
const ui_theme_variable_t _ui_theme_color_atmoBtn[6]     = {ATMO, BTNCLO, BTNCLO, BTNCLO, BTNCLO, BTNCLO};
const ui_theme_variable_t _ui_theme_alpha_atmoBtn[6]     = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};

const ui_theme_variable_t _ui_theme_color_movieBtn[6]    = {BTNCLO, MOVIE, BTNCLO, BTNCLO, BTNCLO, BTNCLO};
const ui_theme_variable_t _ui_theme_alpha_movieBtn[6]    = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};

const ui_theme_variable_t _ui_theme_color_romanBtn[6]    = {BTNCLO, BTNCLO, ROMAN, BTNCLO, BTNCLO, BTNCLO};
const ui_theme_variable_t _ui_theme_alpha_romanBtn[6]    = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};

const ui_theme_variable_t _ui_theme_color_starryBtn[6]   = {BTNCLO, BTNCLO, BTNCLO, STARRY, BTNCLO, BTNCLO};
const ui_theme_variable_t _ui_theme_alpha_starryBtn[6]   = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};

const ui_theme_variable_t _ui_theme_color_dailyBtn[6]    = {BTNCLO, BTNCLO, BTNCLO, BTNCLO, DAILY, BTNCLO };
const ui_theme_variable_t _ui_theme_alpha_dailyBtn[6]    = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};
//标签的主题色彩设置
const ui_theme_variable_t _ui_theme_color_atmoBtnLab[6]     = {ONCHECK, LABCLO, LABCLO, LABCLO, LABCLO, LABCLO};
const ui_theme_variable_t _ui_theme_alpha_atmoBtnLab[6]     = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};

const ui_theme_variable_t _ui_theme_color_movieBtnLab[6]    = {LABCLO, ONCHECK, LABCLO, LABCLO, LABCLO, LABCLO};
const ui_theme_variable_t _ui_theme_alpha_movieBtnLab[6]    = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};

const ui_theme_variable_t _ui_theme_color_romanBtnLab[6]    = {LABCLO, LABCLO, ONCHECK, LABCLO, LABCLO, LABCLO};
const ui_theme_variable_t _ui_theme_alpha_romanBtnLab[6]    = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};

const ui_theme_variable_t _ui_theme_color_starryBtnLab[6]   = {LABCLO, LABCLO, LABCLO, ONCHECK, LABCLO, LABCLO};
const ui_theme_variable_t _ui_theme_alpha_starryBtnLab[6]   = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};

const ui_theme_variable_t _ui_theme_color_dailyBtnLab[6]    = {LABCLO, LABCLO, LABCLO, LABCLO, ONCHECK, LABCLO };
const ui_theme_variable_t _ui_theme_alpha_dailyBtnLab[6]    = {ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA};
uint8_t ui_theme_idx = UI_THEME_ATMO;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

