// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

//色彩
#define ATMO    0xD4B8F6
#define MOVIE   0x1D233F
#define ROMAN   0xDE858F
#define STARRY  0x00097A
#define DAILY   0x0079FF
#define ONCHECK 0xFFFFFF
#define BTNCLO  0xECECEC
#define LABCLO  0x939393
#define OFFBTN  0x909090
#define ALPHA   255

//主题色彩
#define UI_THEME_COLOR_EXARC 0
#define UI_THEME_COLOR_INARC 1
#define UI_THEME_COLOR_ATMOBTN 2
#define UI_THEME_COLOR_MOVIEBTN 3
#define UI_THEME_COLOR_ROAMNBTN 4
#define UI_THEME_COLOR_STARRYBTN 5
#define UI_THEME_COLOR_ATMOBTNLAB 6
#define UI_THEME_COLOR_MOVIEBTNLAB 7
#define UI_THEME_COLOR_ROAMNBTNLAB 8
#define UI_THEME_COLOR_STARRYBTNLAB 9

//主题
#define UI_THEME_ATMO 0

#define UI_THEME_MOVIE 1

#define UI_THEME_ROMAN 2

#define UI_THEME_STARRY 3

#define UI_THEME_DAILY 4

#define UI_THEME_OFF 5

//Arc的主题色彩设置
extern const ui_theme_variable_t _ui_theme_color_exarc[6];
extern const ui_theme_variable_t _ui_theme_alpha_exarc[6];
extern const ui_theme_variable_t _ui_theme_color_inarc[6];
extern const ui_theme_variable_t _ui_theme_alpha_inarc[6];
extern const ui_theme_variable_t _ui_theme_color_offbtn[6];
extern const ui_theme_variable_t _ui_theme_alpha_offbtn[6];
//按钮的主题色彩设置
extern const ui_theme_variable_t _ui_theme_color_atmoBtn[6];
extern const ui_theme_variable_t _ui_theme_alpha_atmoBtn[6];

extern const ui_theme_variable_t _ui_theme_color_movieBtn[6];
extern const ui_theme_variable_t _ui_theme_alpha_movieBtn[6];

extern const ui_theme_variable_t _ui_theme_color_romanBtn[6];
extern const ui_theme_variable_t _ui_theme_alpha_romanBtn[6];

extern const ui_theme_variable_t _ui_theme_color_starryBtn[6];
extern const ui_theme_variable_t _ui_theme_alpha_starryBtn[6];

extern const ui_theme_variable_t _ui_theme_color_dailyBtn[6];
extern const ui_theme_variable_t _ui_theme_alpha_dailyBtn[6];
//标签的主题色彩设置
extern const ui_theme_variable_t _ui_theme_color_atmoBtnLab[6];
extern const ui_theme_variable_t _ui_theme_alpha_atmoBtnLab[6];

extern const ui_theme_variable_t _ui_theme_color_movieBtnLab[6];
extern const ui_theme_variable_t _ui_theme_alpha_movieBtnLab[6];

extern const ui_theme_variable_t _ui_theme_color_romanBtnLab[6];
extern const ui_theme_variable_t _ui_theme_alpha_romanBtnLab[6];

extern const ui_theme_variable_t _ui_theme_color_starryBtnLab[6];
extern const ui_theme_variable_t _ui_theme_alpha_starryBtnLab[6];

extern const ui_theme_variable_t _ui_theme_color_dailyBtnLab[6];
extern const ui_theme_variable_t _ui_theme_alpha_dailyBtnLab[6];

extern const uint32_t* ui_theme_colors[6];
extern const uint8_t* ui_theme_alphas[6];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
